spring.application.name=dogs-api

# JWT Configuration
jwt.secret=PerrosSocialSuperSecretKey2026ForJWTTokenGenerationAndValidation
jwt.expiration=86400000

# Configuración CORS adicional
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Cloudinary Configuration
cloudinary.cloud-name=dwhh2yudk
cloudinary.api-key=519635949513165
cloudinary.api-secret=mta_hnS71XFhu1xjOR2_anN_-Sk
cloudinary.folder=dogs_app

# Configuración para archivos grandes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuración de PostgreSQL para DOCKER
spring.datasource.url=jdbc:postgresql://172.17.0.1:5432/dogs_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuración de JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
