kspring.application.name=dogs-api

# Configuración de PostgreSQL para DOCKER
spring.datasource.url=jdbc:postgresql://172.17.0.1:5432/dogs_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuración de JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
